[package]
name = "simple_wintun"
version = "0.1.0"
authors = ["xutianyi <853122726@qq.com>"]
edition = "2018"
description = "Wintun rust API library"
license = "MIT OR Apache-2.0"

[build-dependencies]
cc = "1"

[dependencies]
once_cell = "1"
log = "0.4"